### ISSUE TITLE
New Member here ....

### ISSUE THREAD

**Issue by Tw2CeYoU** [b0th/CTF#1]
Hi, I recently joined the `__T3TR4H3DR0N__` team in ctftime.org

Please tell me about the communication method you guys use so that I can solve with you...

**Comment by b0th** [comment]
Hey, welcome :).
Add me via discord : b0th#2965

**Comment by b0th** [comment]
Hey, welcome :)
Add me via discord : **b0th#2965**

**Comment by Tw2CeYoU** [comment]
sorry for being late ...
I thought you all already have your slack or discord groups .....

slack link : https://join.slack.com/t/t3trah3dr0n/shared_invite/enQtODI1NzMxMTQzMDYzLWVhZGM3OTBjZjMxZDUwMmU5ODYzNDc5ZGJiOGI4NGU5MDIwMWQxODZlOGNkNTVhZDE3N2ZiYzBkY2VhNjJiMTI (I actually prefer slack)
discord link : https://discord.gg/7fnVcEj
